SET IDENTITY_INSERT [dbo].[tbl_MenuItem] ON
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (2, 2, 0, N'Đồ bơi nữ', N'/do-boi-nu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (3, 2, 2, N'Đồ bơi tay dài nữ', N'/do-boi-nu/tay-dai-nu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (4, 2, 2, N'Áo bơi nữ', N'/do-boi-nu/ao-boi')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (5, 2, 4, N'Áo bơi tay dài', N'/do-boi-nu/ao-boi/tay-dai')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (6, 2, 4, N'Áo bơi bra top', N'/do-boi-nu/ao-boi/bra-top')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (7, 2, 2, N'Quần bơi nữ', N'/do-boi-nu/quan-boi')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (8, 2, 7, N'Quần bơi dài', N'/do-boi-nu/quan-boi/dai')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (9, 2, 7, N'Quần bơi ngắn', N'/do-boi-nu/quan-boi/ngan')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (10, 2, 2, N'Set đồ bơi nữ', N'/do-boi-nu/set')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (11, 2, 0, N'Đồ bơi nam', N'/do-boi-nam')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (12, 2, 0, N'Đồ bơi cặp', N'/do-boi-cap')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (13, 2, 0, N'Giới thiệu', N'/gioi-thieu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (14, 2, 0, N'Blog', N'/blog')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (15, 2, 0, N'Liên hệ', N'/lien-he')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (16, 1, 0, N'Giới thiệu', N'/gioi-thieu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (17, 1, 0, N'Hướng dẫn', N'/huong-dan')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (18, 1, 0, N'Bảng size', N'/bang-size')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (19, 1, 0, N'Đổi trả hàng', N'/doi-tra-hang')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (20, 3, 0, N'Đồ bơi nữ', N'/do-boi-nu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (21, 3, 0, N'Đồ bơi nam', N'/do-boi-nam')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (22, 3, 0, N'Đồ bơi cặp', N'/do-boi-cap')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (23, 3, 0, N'Giới thiệu', N'/gioi-thieu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (24, 3, 0, N'Blog', N'/blog')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (25, 3, 0, N'Liên hệ', N'/lien-he')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (26, 4, 0, N'Đồ bơi nữ', N'/do-boi-nu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (27, 4, 0, N'Đồ bơi nam', N'/do-boi-nam')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (28, 4, 0, N'Đồ bơi cặp', N'/do-boi-cap')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (29, 4, 0, N'Giới thiệu', N'/gioi-thieu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (30, 4, 0, N'Blog', N'/blog')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (31, 4, 0, N'Liên hệ', N'/lien-he')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (32, 5, 0, N'Đồ bơi nữ', N'/do-boi-nu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (33, 5, 0, N'Đồ bơi nam', N'/do-boi-nam')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (34, 5, 0, N'Đồ bơi cặp', N'/do-boi-cap')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (35, 5, 0, N'Giới thiệu', N'/gioi-thieu')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (36, 5, 0, N'Blog', N'/blog')
INSERT INTO [dbo].[tbl_MenuItem] ([ID], [MenuID], [ParentID], [Name], [URL]) VALUES (37, 5, 0, N'Liên hệ', N'/lien-he')
SET IDENTITY_INSERT [dbo].[tbl_MenuItem] OFF
