SET IDENTITY_INSERT [dbo].[tbl_ProductImage] ON
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (1, 13, N'http://localhost/ann-shop/images/0530_la_07_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_la_07_small.jpg', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (2, 13, N'http://localhost/ann-shop/images/0530_la_12_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_la_12_small.jpg', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (3, 13, N'http://localhost/ann-shop/images/0530_la_76_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_la_76_small.jpg', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (4, 13, N'http://localhost/ann-shop/images/0530_la_02_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_la_02_small.jpg', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (5, 13, N'http://localhost/ann-shop/images/0530_rg1_sp1_06_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_rg1_sp1_06_small.jpg', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (6, 13, N'http://localhost/ann-shop/images/0530_la_33_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_la_33_small.jpg', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (7, 13, N'http://localhost/ann-shop/images/0530_la_49_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_la_49_small.jpg', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[tbl_ProductImage] ([ID], [ProductID], [Filename], [Title], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (8, 13, N'http://localhost/ann-shop/images/0530_la_25_1024x1024.jpg', N'http://localhost/ann-shop/images/0530_la_25_small.jpg', NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[tbl_ProductImage] OFF
