CREATE TABLE [dbo].[tbl_Product] (
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
	[SystemID]		   INT      NULL,
    [SKU]              NVARCHAR (25)  NOT NULL,
    [Name]             NVARCHAR (250) NOT NULL,
    [ShortDescription] NVARCHAR (MAX) NULL,
    [Content]          NVARCHAR (MAX) NULL,
    [Materials]        NVARCHAR (250) NULL,
    [Type]             NVARCHAR (20)  NOT NULL,
    [Slug]             NVARCHAR (250) NOT NULL,
    [WholesalePrice]   FLOAT (53)     NULL,
    [RetailPrice]      FLOAT (53)     NULL,
    [CostOfGoods]      FLOAT (53)     NULL,
    [ManageStock]      INT            NULL,
    [StockStatus]      INT            NULL,
    [Status]           INT            NULL,
    [CommentSatus]     INT            NULL,
    [Image]            NVARCHAR (250) NULL,
    [Featured]         INT            NULL,
    [ViewCount]        INT            NULL,
	[Export]           INT            NULL,
    [Hidden]           INT            NULL,
    [MetaTitle]        NVARCHAR (250) NULL,
    [MetaDescription]  NVARCHAR (MAX) NULL,
    [CreatedBy]        INT            NULL,
    [CreatedDate]      DATETIME       NULL,
    [ModifiedBy]       INT            NULL,
    [ModifiedDate]     DATETIME       NULL,
    CONSTRAINT [PK_tbl_Product] PRIMARY KEY CLUSTERED ([ID] ASC)
);

