CREATE TABLE [dbo].[tbl_Order] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [SystemID]   INT            NULL,
    [SystemUsername]  NVARCHAR (50)  NULL,
    [Type]            INT            NULL,
    [CustomerID]      INT            NULL,
    [CustomerName]    NVARCHAR (100) NOT NULL,
    [CustomerPhone]   NVARCHAR (15)  NOT NULL,
    [CustomerPhone2]  NVARCHAR (15)  NULL,
    [CustomerAddress] NVARCHAR (200) NULL,
    [CustomerEmail]   NVARCHAR (200) NULL,
    [CustomerAccept]  INT            NULL,
    [Note]            NVARCHAR (250) NULL,
    [Subtotal]        FLOAT (53)     NULL,
    [ShippingFee]     FLOAT (53)     NULL,
    [TotalDiscount]   FLOAT (53)     NULL,
    [DiscountPerItem] FLOAT (53)     NULL,
    [OtherFeeName]    NVARCHAR (100) NULL,
    [OtherFeeValue]   FLOAT (53)     NULL,
    [RefundOrderID]   INT            NULL,
    [RefundFee]       FLOAT (53)     NULL,
    [Total]           FLOAT (53)     NULL,
    [ExcuteStatus]    INT            NULL,
    [PaymentStatus]   INT            NULL,
    [PaymentMethod]   INT            NULL,
    [TransportMethod] INT            NULL,
    [ShippingCode]    NVARCHAR (100) NULL,
    [DoneDate]        DATETIME       NULL,
    [CreatedBy]       INT            NULL,
    [CreatedDate]     DATETIME       NULL,
    [ModifiedBy]      INT            NULL,
    [ModifiedDate]    DATETIME       NULL,
    CONSTRAINT [PK_tbl_Order] PRIMARY KEY CLUSTERED ([ID] ASC)
);

