//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ann_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductVariantValue
    {
        public int ID { get; set; }
        public int VariantID { get; set; }
        public string VariantSKU { get; set; }
        public int AttributeID { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
