//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ann_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comment
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int PostID { get; set; }
        public string PostType { get; set; }
        public string Author { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Content { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> Hidden { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
