//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ann_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MenuItem
    {
        public int ID { get; set; }
        public int MenuID { get; set; }
        public int ParentID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
    }
}
