//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ann_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public int ID { get; set; }
        public Nullable<int> SystemOrderID { get; set; }
        public string SystemUsername { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerPhone2 { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<int> CustomerAccept { get; set; }
        public string Note { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> ShippingFee { get; set; }
        public Nullable<double> TotalDiscount { get; set; }
        public Nullable<double> DiscountPerItem { get; set; }
        public string OtherFeeName { get; set; }
        public Nullable<double> OtherFeeValue { get; set; }
        public Nullable<int> RefundOrderID { get; set; }
        public Nullable<double> RefundFee { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> ExcuteStatus { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<int> TransportMethod { get; set; }
        public string ShippingCode { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
